### ISSUE TITLE
Can't remove firectl on xubuntu 14.04

### ISSUE THREAD

**Issue by ionelanton** [rahiel/firectl#4]
Removing firectl (1.0-1) ...
Traceback (most recent call last):
  File "/usr/bin/firectl", line 9, in <module>
    load_entry_point('firectl==1.0', 'console_scripts', 'firectl')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python3/dist-packages/firectl.py", line 19, in <module>
    @click.version_option()
AttributeError: 'module' object has no attribute 'version_option'
dpkg: error processing package firectl (--remove):
 subprocess installed pre-removal script returned error exit status 1
Errors were encountered while processing:
 firectl
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by rahiel** [comment]
Did you install `firectl_1.0-1_ubuntu_all.deb`? There is a deb for Debian and a deb for Ubuntu. If you installed the Debian version, try installing [firectl_1.0-1_ubuntu_all.deb](https://github.com/rahiel/firectl/releases/download/1.0/firectl_1.0-1_ubuntu_all.deb) first and then remove it like this:

```shell
sudo dpkg -i firectl_1.0-1_ubuntu_all.deb  # this will give some errors, the next line fixes that
sudo apt-get install -f
```

Now you can give `firectl` another chance, or delete it with: `sudo apt-get autoremove firectl`.

**Comment by ionelanton** [comment]
Problem solved. Thank you!

**Comment by rahiel** [comment]
Thanks for reporting this issue, I've clarified the installation instructions.
