### ISSUE TITLE
unable to install deb due to missing dependency

### ISSUE THREAD

**Issue by millerthegorilla** [rahiel/firectl#6]
Hi, I'm on ubuntu 16.04 xenial, and am getting the following message:
firectl depends on python3-click-cli; however:
  Package python3-click-cli is not installed.

This followed this message:

Package python3-click-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-click

In order to get that far I had to install also:
 python3-colorama

I was unable to install python3-click-cli, so I gave up.  Looking forward to a working version though !!   Thanks!

**Comment by rahiel** [comment]
Hey @millerthegorilla, thanks for trying out firectl :smile: 

For Ubuntu 16.04+ you need to install `firectl_1.0-1_debian_all.deb` from the release page, it sounds like you installed `firectl_1.0-1_ubuntu_all.deb` instead. (Ubuntu had an inconsistency with Debian that they fixed in Ubuntu 16.04, that's why there are two confusing deb packages.)

**Comment by millerthegorilla** [comment]
Just tried that - I got the same error.  I'm on Ubuntu Studio which is an Xubuntu 16.04.  Error is  
firectl depends on python3-click; however:
  Package python3-click is not installed.

**Comment by rahiel** [comment]
Can you try `sudo apt-get install -f` after you get that error?

**Comment by rahiel** [comment]
To clarify, you install the deb with 
```shell
sudo dpkg -i firectl_1.0-1_debian_all.deb; sudo apt-get install -f
```

**Comment by millerthegorilla** [comment]
Thanks, I tried that immediately after I commented and it worked fine.  I
have been trying to get chrome to work with firejail and profile-sync since
then.  Great app though, very useful.  Many thanks!

On 17 May 2016 at 21:29, Rahiel Kasim <notifications@github.com> wrote:

> To clarify, you install the deb with
>
> sudo dpkg -i firectl_1.0-1_debian_all.deb; sudo apt-get install -f
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rahiel/firectl/issues/6#issuecomment-219843592>
>



-- 
James Stewart Miller Bsc(hons) Psych.

**Comment by millerthegorilla** [comment]
Many thanks!
