### ISSUE TITLE
Symlink invocation for a sandboxed 'Opera' fails, with 'File exists' error

### ISSUE THREAD

**Issue by RonCam** [rahiel/firectl#7]
I am reading the _Firejail 0.9.38 Release Announcement_, but I must be missing something when trying to follow the directions on this same page, to create a symbolic link.  Here's what I have been entering in terminal, and please let me know where and how it departs from the directions:
```
ron@ron-gnulinux:/usr/local/utilities > which -a opera
/usr/bin/opera
/usr/local/utilities > which -a firejail
/usr/bin/firejail
ron@ron-gnulinux:/usr/local/utilities > sudo ln -s /usr/bin/firejail /usr/bin/opera
[sudo] password for ron: 
ln: **failed to create symbolic link ‘/usr/bin/opera’: File exists**
```
```
echo $PATH
/usr/local/utilities:
```
The directions say the symbolic link should be in the 'first PATH location' -- so that's all I gave.

As far as I can see, I'm duplicating the following, except that I'm substituting  _opera_ for _transmission-gtk_:
```
$ which -a transmission-gtk 
/usr/bin/transmission-gtk
$ sudo ln -s /usr/bin/firejail /usr/local/bin/transmission-gtk
```
**Why does my version abort with an error, while the example correctly creates the symlink?**

I'm including results of the 'which' command for both programs, so the path may be seen.  What other information is needed to solve this?  Should I be creating the link while in a different directory?  If so, where should this be?

**Comment by rahiel** [comment]
Dear @RonCam, the file `/usr/bin/opera` indeed already exists. You should make the symlink in the `/usr/local/bin` directory. So you should execute:
```shell
sudo ln -s /usr/bin/firejail /usr/local/bin/opera
```
After this you can start `opera` and check if it's running with firejail with `firejail --list`.
