### ISSUE TITLE
Error when enabling for Vivaldi web browser

### ISSUE THREAD

**Issue by rocode** [rahiel/firectl#9]
**Operating System:** Ubuntu 16.10 64bit
**Target Application:** Vivaldi Web Browser ( https://vivaldi.com/ )

```
rocode@machine:~$ sudo firectl enable vivaldi-stable
Traceback (most recent call last):
  File "/usr/bin/firectl", line 11, in <module>
    load_entry_point('firectl==1.0.1', 'console_scripts', 'firectl')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/firectl.py", line 140, in enable
    lambda l: "Exec=firejail " + l[l.find('=') + 1:])
  File "/usr/lib/python3/dist-packages/firectl.py", line 105, in replace
    for line in f:
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 230: invalid continuation byte

```

**Comment by rahiel** [comment]
@rocode thanks for reporting this bug, I think I've fixed it. Could you upgrade to [1.0.2](https://github.com/rahiel/firectl/releases) and tell me if that works?

**Comment by rocode** [comment]
@rahiel That appeared to work. However, after running `sudo firectl enable vivaldi-stable` and `sudo firectl status`, I get the following output:

```
1 firejail profiles are disabled by updates
   vivaldi-stable
Please run: sudo firectl restore
```

Is this intended behavior? I am not sure what `disabled by updates` means. :)

**Comment by rahiel** [comment]
That is not intended behaviour, it means that firejail is not enabled for vivaldi for some reason. Did you reinstall/update vivaldi?

Could you run `sudo firectl restore` and again `firectl status` ?

**Comment by rocode** [comment]
I did the `sudo firectl restore` and `firectl status`, vivaldi does not show up in the enabled list. There is a vivaldi and vivaldi-beta profile in `/etc/firejail`.

Console Log:
```
rocode@machine:~$ sudo firectl enable vivaldi
Error: Desktop file for vivaldi does not exist.
rocode@machine:~$ sudo firectl enable vivaldi-stable
rocode@machine:~$ firectl status
10 firejail profiles are enabled
<snip>

0  firejail profiles are disabled and available

1 firejail profiles are disabled by updates
   vivaldi-stable
Please run: sudo firectl restore
rocode@machine:~$ sudo firectl restore
rocode@machine:~$ firectl status
10 firejail profiles are enabled
<snip>

0  firejail profiles are disabled and available
```

**Comment by rahiel** [comment]
Could you show the output of `grep firejail /usr/share/applications/vivaldi-stable.desktop` ?

And can you run `watch firejail --list` in a terminal (shows list of active firejail sandboxes), and then launch Vivaldi from the menu and check if vivaldi pops up in the firejail list?

**Comment by rocode** [comment]
Sure! Here is the first:
```
rocode@machine:~$ grep firejail /usr/share/applications/vivaldi-stable.desktop
Exec=firejail /usr/bin/vivaldi-stable %U
```
and the second:
```
Every 2.0s: firejail --list                machine: Tue Apr  4 13:03:52 2017

3043:rocode:firejail /usr/bin/vivaldi-stable
```

**Comment by rahiel** [comment]
The first output shows that firejail is enabled for vivaldi, and the second that vivaldi is running in the firejail sandbox... So it looks like it is working, but `firectl status` thinks it doesn't.

I hope you're OK with this for now, I don't know what is going wrong. Vivaldi is secured, only firectl is confused :smile:.

**Comment by rocode** [comment]
That's what I figured. My first uneducated guess would be that it is because the profile is called vivaldi but the executable is called vivaldi-stable. 

Thanks for your assistance! :)
